name: Bin Tests

on:
  push:
    branches:
      - main
  pull_request: ~

jobs:
  unit_tests:
    strategy:
      matrix:
        php:
          - '8.2'
          - '8.3'
          - '8.4'
          - '8.5'

    runs-on: ubuntu-latest

    name: "PHP ${{ matrix.php }} tests"
    
    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: pcov

      - uses: "ramsey/composer-install@v2"
        
      - run: chmod +x ./bin/x-graphql-codegen

      - run: ./bin/x-graphql-codegen
